---
title:tanforu
---
# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: "http://mattcouchman.co.uk/jekyll-resume/"
url: "http://mattcouchman.co.uk/jekyll-resume/"
name: Tanforu
job: Student
location: Guangzhou,China
languages: HTML, CSS and Javascript
twitter_username: mattcouchman
github_username:  mattcouchman
codepen_username:  mattcouchman
email_address: some@email.com

# Build settings
markdown: kramdown
