# Jekyll Resume Theme

# Site settings
title: Han-Teng Liao
email: hanteng@gmail.com
description: Demo of using Jekyll Resume, a simple resume theme for Jekyll.
baseurl: "/jekyll-resume"
url: "https://hanteng.gitee.io"
name: Han-Teng Liao
job: Associate Professor
location: Guangzhou, China
languages: Python, People-Centered HCI and Sustainable Development Goals
twitter_username: hanteng
github_username:  hanteng
codepen_username:  hanteng
email_address: h.liao@oxon.org

# Build settings
markdown: kramdown
